### ISSUE TITLE
Is defining custom headers considered ?

### ISSUE THREAD

**Issue by TristanPouliquen** [AppVentus/AvSpoolMailerBundle#12]
Hello,

Do you have considered on a short term to manage the setting of custom headers ? ([examples in Swiftmailer](https://hotexamples.com/examples/-/Swift_Message/getHeaders/php-swift_message-getheaders-method-examples.html#0x358c23e80dd47e7fd0b1d04b71b6dc98bf7cb4256a0537008923cd864cf9baf9-42,,80,) )

Useful features for example when working with mail automation tools that allow unsubscription management on a finer level with tags (Mailgun for example).

**Comment by lenybernard** [comment]
Closed by https://github.com/AppVentus/AvSpoolMailerBundle/pull/13 🎊
